parameters:
- name: environment
  type: string
- name: namespace
  type: string        
- name: ingressHostName
  type: string
- name: dbpassword
  type: string
- name: trafficManagerEnabled
  type: string
- name: trafficManagerDNS
  type: string      
  
jobs:    
  - deployment: Deploy
    displayName: Deploy
    environment: '${{ parameters.environment }}'    
    strategy:
      runOnce:
        deploy:
          steps:
          - reviewApp: qbox

          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'

          - task: HelmInstaller@0
            inputs:
              helmVersion: '3.4.2'
              installKubectl: true
              
          - task: HelmDeploy@0
            inputs:
              namespace: $(k8sNamespaceForPR)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/drop/qbox-$(Build.BuildNumber).tgz'
              releaseName: 'quizbox-$(k8sNamespaceForPR)'
              overrideValues: 'frontend.image.tag=$(Build.BuildNumber),backend.image.tag=$(Build.BuildNumber),ingress.hostname=${{ parameters.ingressHostName }},db.service.port=1433,db.password=${{ parameters.dbpassword }},ingress.trafficManagerEnabled=${{ parameters.trafficManagerEnabled }},ingress.trafficManagerDNS=${{ parameters.trafficManagerDNS }}'
              arguments: --atomic
              