apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-canary
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      tier: frontend
      mode: canary
  template:
    metadata:
      labels:
        tier: frontend
        mode: canary
    spec:
      containers:
      - name: frontend-canary
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        resources:
          requests:
            cpu: 200m          
          limits:
            cpu: 500m

