apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  labels:
    tier: frontend
    mode: canary
spec:
  selector:
    tier: frontend
    mode: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
