name: 2.2$(rev:.r)

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  ingressHostName: aksdemo.ehn.nu
  ingressHostNameCanary: aksdemo-canary.ehn.nu
  dbPassword: 1qaz2WSX3edc

stages:

- stage: Build
  displayName: Build

  jobs:
  - job: Build
    displayName: Build  
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Microsoft Azure Sponsorship(b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5)'
        azureContainerRegistry: '{"loginServer":"jakob.azurecr.io", "id" : "/subscriptions/b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5/resourceGroups/acr/providers/Microsoft.ContainerRegistry/registries/jakob"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        additionalImageTags: '$(build.buildnumber)'
        includeLatestTag: true

    - task: DockerCompose@0
      displayName: 'Push images'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Microsoft Azure Sponsorship(b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5)'
        azureContainerRegistry: '{"loginServer":"jakob.azurecr.io", "id" : "/subscriptions/b7b2c6f7-b71e-4cd2-9e7c-409a44fe22f5/resourceGroups/acr/providers/Microsoft.ContainerRegistry/registries/jakob"}'
        action: 'Push services'
        additionalImageTags: '$(build.buildnumber)'        
      
    - task: HelmInstaller@1
      displayName: Install Helm 3.4.2
      inputs:
        helmVersionToInstall: '3.4.2'
        
    - task: HelmDeploy@0
      displayName: 'Package Helm chart'
      inputs:
        command: 'package'
        chartPath: 'demoscripts/deployment/helm/qbox'
        chartVersion: '$(build.buildnumber)'        

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Helm chart artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  variables:
  - group: quizbox-dev

  jobs:    
  - deployment: Deploy
    displayName: Deploy
    environment: 'aksdemo'
    strategy:
      runOnce:
        deploy:
          steps:  
          - task: HelmInstaller@0
            inputs:
              helmVersion: '3.4.2'
              installKubectl: true

          - task: HelmDeploy@0
            displayName: 'Deploy QBox Helm chart'
            inputs:
              namespace: default
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/drop/qbox-$(Build.BuildNumber).tgz'
              releaseName: 'quizbox'
              overrideValues: 'frontend.image.tag=$(Build.BuildNumber),backend.image.tag=$(Build.BuildNumber),ingress.hostname=$(ingressHostName),ingress.hostname-canary=$(ingressHostNameCanary),db.service.port=1433,db.password=$(dbPassword)'
              arguments: --atomic
              


