kubectl delete deploy frontend
kubectl delete deploy frontend-canary
kubectl delete deploy backend
kubectl delete deploy db
kubectl delete svc frontend
kubectl delete svc frontend-canary
kubectl delete svc api
kubectl delete svc db
kubectl delete ingress aksdemo
kubectl delete secret db-storage