apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      mode: canary

  template:
    metadata:
      labels:
        tier: frontend    
        mode: canary
    spec:
      containers:
      - name: frontend-canary
        image: jakob.azurecr.io/qboxcoreweb:0.8
---
kind: Service
apiVersion: v1
metadata:
  name:  frontend-canary
spec:
  selector:
    tier: frontend
    mode: canary
  type:  ClusterIP
  ports:
    - protocol: TCP
      port: 80