apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      mode: production
  template:
    metadata:
      labels:
        tier: frontend
        mode: production
    spec:
      containers:
      - name: frontend
        image: jakob.azurecr.io/qboxcoreweb:0.7
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"         
          
---
kind: Service
apiVersion: v1
metadata:
  name:  frontend
spec:
  selector:
    tier: frontend
    mode: production

  type:  ClusterIP
  ports:
    - protocol: TCP
      port: 80