# Default values for qboxchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
frontend: 
  image:
    repository: jakob.azurecr.io/qboxcoreweb
    tag: "2.1.102"
    pullPolicy: IfNotPresent
  containerPort: 80    

  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: jakob.azurecr.io/qboxcoreapi
    tag: "2.1.102"
    pullPolicy: IfNotPresent
  containerPort: 80

db:
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "2017-latest"
    pullPolicy: IfNotPresent
  service: 
    port: 80    

