apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbox-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: frontend
            port:
              number: 80

{{ if .Values.ingress.trafficManagerEnabled}}
  - host: {{ .Values.ingress.trafficManagerDNS }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: frontend
            port:
              number: 80
{{ end }}