apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbox
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: qbox
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: jakob.azurecr.io/qboxcoreweb:2.2.50
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     cpu: "250m"                   
        #   limits:
        #     cpu: "500m"  
        
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 80
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
           
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP